FROM scratch
MAINTAINER Jerry Hicks <jhicks@camgian.com>
ADD root.tar /
RUN apt-get update \
	&& apt-get -y upgrade \
	&& apt-get -y autoremove \
	&& apt-get clean \
	&& find /var/lib/apt/lists -type f -delete
LABEL com.camgian.docker.VcsType git
LABEL com.camgian.docker.VcsUrl  http://github.com/jhicks-camgian/ubuntu-docker
LABEL com.camgian.docker.VcsRef  SUBSTITUTION_FAILED
CMD ["/bin/bash"]
